[project]
authors = ["Martin Dudek <martin.dudek@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "port of Andrjey Karpathy's minbpe to Mojo"
name = "minbpe.mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
regex = "*" 

[feature.nightly]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]

[feature.nightly.dependencies]
max = "*"

[feature.stable]

[feature.stable.dependencies]
max = ">=24.5,<24.6"

[feature.old]

[feature.old.dependencies]
max = "==24.4.0"

[environments]
default = ["stable"]
nightly = ["nightly"]
mojo-24-4 = ["old"]
